version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - '8080:80' # Portweiterleitung: Auf Port 8080 auf dem Host zugänglich machen
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html # Passe den Pfad zur HTML-Datei an
