# Verwende ein Nginx-Base-Image
FROM nginx:alpine

# Kopiere die HTML-Datei in den Nginx-Ordner, der für das Servieren von Inhalten verwendet wird
COPY index.html /usr/share/nginx/html

# Exponiere den Port 80, auf dem der Webserver laufen wird
EXPOSE 80
